swagger: '2.0'
info:
  title: Chat Application API
  version: '1.0'
schemes:
  - http
  - https
produces:
  - application/json
x-google-backend:
  address: https://summaryapi-image-nhz45gwa6a-uc.a.run.app
security:
  - api_key: []  # Add an empty API key requirement for all operations
paths:
  /palm2:
    post:
      summary: Start a chat session and get a response
      operationId: startChatPost
      parameters:
        - name: user_input
          in: formData
          description: User input for the chat session
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              content:
                type: string
    get:
      summary: Start a chat session and get a response (using query parameter)
      operationId: startChatGet
      parameters:
        - name: user_input
          in: query
          description: User input for the chat session
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              content:
                type: string